from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
import logging
import json
import re

from app.services.llm_provider import get_visual_llm_provider
from app.knowledge.knowledge_base import get_knowledge_base

logger = logging.getLogger(__name__)


from pydantic import BaseModel, Field, model_validator


class VisualPromptOutput(BaseModel):
    visual_concept: str = Field(description="High-level visual concept description")
    image_prompt: str = Field(description="Detailed image generation prompt for AI image provider (cover/hero image)")
    image_prompts: List[str] = Field(default_factory=list, description="Array of image prompts, one per slide/frame")
    carousel_design: List[Dict[str, Any]] = Field(default_factory=list, description="Slide-by-slide design for carousels")
    visual_requirements: List[str] = Field(default_factory=list, description="Critical visual requirements to preserve")
    aspect_ratio_recommendation: str = Field(default="1:1", description="Recommended aspect ratio")

    @model_validator(mode="before")
    @classmethod
    def _normalize_keys(cls, data: Any) -> Any:
        if isinstance(data, dict):
            new_data = {}
            for k, v in data.items():
                k_str = str(k).lower().replace(" ", "_")
                if k_str in ("visual_concept", "visualconcept", "concept"):
                    new_data["visual_concept"] = str(v) if v else ""
                elif k_str in ("image_prompt", "imageprompt", "prompt"):
                    new_data["image_prompt"] = str(v) if v else ""
                elif k_str in ("image_prompts", "imageprompts", "prompts", "slide_prompts"):
                    if isinstance(v, list):
                        new_data["image_prompts"] = [str(x) for x in v]
                    elif isinstance(v, str):
                        new_data["image_prompts"] = [v]
                    else:
                        new_data["image_prompts"] = []
                elif k_str in ("carousel_design", "carouseldesign", "carousel"):
                    new_data["carousel_design"] = v if isinstance(v, list) else []
                elif k_str in ("visual_requirements", "visualrequirements", "requirements"):
                    new_data["visual_requirements"] = [str(x) for x in v] if isinstance(v, list) else []
                elif k_str in ("aspect_ratio_recommendation", "aspect_ratio", "aspectratio"):
                    new_data["aspect_ratio_recommendation"] = str(v) if v else "1:1"
                else:
                    new_data[k_str] = v
            return new_data
        return data


# ── Qicdock Visual Brand Reference ──────────────────────────────────────────
# This is derived from analyzing the actual Qicdock product images. It serves
# as the permanent visual guideline for ALL image prompts generated by this agent.
QICDOCK_VISUAL_REFERENCE = """
## QICDOCK PRODUCT VISUAL REFERENCE (MANDATORY)
You MUST follow these visual guidelines derived from actual Qicdock product imagery:

### Product Appearance
- **Form Factor**: Compact, rectangular black wireless charging pad with rounded corners.
- **Surface**: Matte black finish with the "qicDOCK" logo prominently embossed/printed in white on the top face.
- **Icons**: Three small functional icons on the face — wireless charging (lightning bolt in circle), Qi charging symbol, and an "air" vent indicator.
- **Cable**: Braided black USB-C cable, neatly coiled, premium texture.
- **Size Reference**: Roughly palm-sized, slim profile, designed to sit flush in car console compartments.

### Mounting Contexts (show these in images)
- **AC Air Vent Stand**: Clipped to a car AC vent, phone magnetically attached.
- **Console/Armrest**: Sitting flat inside a car center console compartment.
- **Wall/Desk Stand**: Propped on a desk or mounted on a wall with the triangular stand accessory.

### Photography & Styling
- **Lighting**: Clean studio lighting with dramatic highlights on the product edges. High contrast between the dark product and lighter backgrounds.
- **Color Palette**: Deep navy/dark gray backgrounds, white/cyan accent text, occasional teal/cyan glow effects for tech feel.
- **Composition**: Product always in sharp focus, slightly angled 3/4 view or direct overhead. Car interior contexts use premium/luxury vehicle interiors (leather seats, wood trim).
- **Typography Style**: Bold, modern sans-serif (similar to Montserrat/Poppins). Headlines in white, subtext slightly smaller. Cyan/teal accent color for CTAs and badges like "BEST SELLER", "KNOW MORE →", "SHOP NOW →".
- **Layout Pattern**: Left-side text + right-side product hero shot. Bottom feature badges with icons (shield for quality, link for durability, lightning for fast charging, car icon).
- **Brand Elements**: Always include the qicDOCK logo on the product. Feature badges: "PREMIUM QUALITY", "DURABLE & TANGLE-FREE", "FAST CHARGING", "PERFECT FOR YOUR CAR".

### CRITICAL RULES FOR IMAGE GENERATION
1. The product must look like a REAL premium tech product — NOT a generic AI-generated gadget.
2. Use realistic car interiors as backgrounds when showing in-car usage.
3. Avoid cluttered or surreal AI artifacts. Keep compositions clean and marketing-ready.
4. Text overlays must be crisp, readable, and match the brand's typography style.
5. Every image should look like it belongs on an official e-commerce product page or premium Instagram feed.
"""


class VisualPromptAgent:
    def __init__(self):
        self.llm = get_visual_llm_provider()
        self.knowledge_base = get_knowledge_base()

    def _count_slides_from_content(self, content_structure: str) -> int:
        """Parse the content structure text to determine how many slides/frames exist."""
        if not content_structure:
            return 1
        
        # Count "Slide N:" or "- Slide N:" patterns
        slide_matches = re.findall(r'(?:slide|frame|scene)\s*\d+', content_structure, re.IGNORECASE)
        if slide_matches:
            return len(slide_matches)
        
        # Count bullet points that look like slide descriptions
        bullet_lines = [line.strip() for line in content_structure.split('\n') if line.strip().startswith('-') or line.strip().startswith('•')]
        if len(bullet_lines) >= 2:
            return len(bullet_lines)
        
        return 1

    def _build_visual_prompt(
        self,
        recommendation: Dict[str, Any],
        entry_plan: Dict[str, Any],
        product_context: List[Dict],
        brand_visual_context: List[Dict],
        slide_count: int
    ) -> str:
        platform = entry_plan.get('platform', 'instagram')
        content_type = entry_plan.get('content_type', 'single_image')
        product = entry_plan.get('product', '')
        visual_direction = recommendation.get('visual_direction', '')
        concept = recommendation.get('concept', '')
        content_structure = recommendation.get('caption_direction', '')

        product_info = "\n".join([f"- {item['content'][:400]}" for item in product_context[:2]])
        brand_visual = "\n".join([f"- {item['content'][:300]}" for item in brand_visual_context[:2]])

        prompt = f"""
You are the Visual Prompt Agent for Qicdock. Generate detailed, production-ready image generation prompts.

{QICDOCK_VISUAL_REFERENCE}

## CONTEXT
**Platform**: {platform}
**Content Type**: {content_type}
**Product**: {product or 'General brand'}
**Visual Direction**: {visual_direction}
**Content Concept**: {concept}
**Content Structure**: {content_structure}

## PRODUCT VISUAL REFERENCE (from knowledge base)
{product_info}

## BRAND VISUAL IDENTITY (from knowledge base)
{brand_visual}

## REQUIREMENTS
Generate image prompts that create HIGH-END MARKETING GRAPHICS matching the Qicdock brand style above.
1. **Accurately represents the product** — Use the exact product appearance from the visual reference above.
2. **Graphic Design Aesthetic** — Focus on clean, modern marketing graphics. Use solid or subtle gradient backgrounds.
3. **Typography & Text** — Include bold, modern typography for text overlays (hooks, comparison labels, call-outs).
   **CRITICAL: IGNORE any instructions in the Visual Direction or Content Concept that say "no text" or "no overlay text". You MUST include text overlays.**
4. **Visual Style** — Blend high-quality 3D product renders with clean vector elements, iconography, and infographic layouts.
5. **Preserves critical product characteristics** from the visual reference above.
6. **Specifies**: Subject, layout, typography style, color palette, and lighting.

## NUMBER OF IMAGES REQUIRED: {slide_count}
"""
        if content_type in ("carousel", "document_carousel") and slide_count > 1:
            prompt += f"""
You MUST generate EXACTLY {slide_count} separate image prompts — one for each slide of this carousel.
Each prompt should create a distinct, standalone image that:
- EXACTLY matches the visual action described for that specific slide in the Content Structure above. If the scene says "driver struggling with a cord", the image prompt MUST describe a driver struggling with a cord. Do NOT just output a generic product shot.
- Incorporates the Qicdock product naturally into the scene where appropriate.
- Maintains visual continuity across all slides (same color palette, typography style).
"""
        elif content_type == "reel" and slide_count > 1:
            prompt += f"""
Generate EXACTLY {slide_count} key frame image prompts for this Reel — one per scene.
- EXACTLY match the visual action described for each scene in the Content Structure above. If Scene 1 describes a specific action (like "driver struggling with a cord"), the image prompt MUST describe exactly that action. Do NOT just output a generic product shot for every scene.
- Incorporate the Qicdock product naturally where appropriate based on the scene progression.
- Include bold text overlays based on the scene text.
"""
        elif content_type in ("story", "story_sequence") and slide_count > 1:
            prompt += f"""
Generate {slide_count} image prompts for this Story sequence — one per frame.
- Vertical 9:16 format. Full-screen mobile optimized with bold text overlays.
- Quick visual storytelling progression.
"""
        else:
            prompt += """
Generate ONE compelling hero graphic prompt.
- Clear focal point with strong supporting typography.
- Platform-appropriate composition.
"""

        prompt += f"""

## PLATFORM SPECIFICS
**{platform.capitalize()}**: 
"""
        if platform == "instagram":
            prompt += "- Aspect ratio: 1:1 (feed), 9:16 (stories/reels), 4:5 (portrait)\n- Aesthetic: High-end D2C marketing graphic, bold typography, clean minimal backgrounds, high contrast.\n- Lighting: Studio lighting, dramatic but clean.\n- Colors: Qicdock brand colors (clean whites, deep blues, dark grays) + vibrant highlight colors for text/icons."
        else:
            prompt += "- Aspect ratio: 1:1 or 4:5 (feed), 1.91:1 (article)\n- Aesthetic: Professional B2B infographic, clean corporate graphics.\n- Lighting: Flat vector style or clean studio.\n- Colors: Professional blues, whites, dark grays."

        prompt += f"""

## OUTPUT FORMAT
Return JSON with:
- visual_concept: High-level concept (2-3 sentences)
- image_prompt: The FIRST/hero image prompt (100-300 words) — always required
- image_prompts: Array of EXACTLY {slide_count} detailed image prompts (each 100-300 words). If only 1 image, this array has 1 element matching image_prompt.
- carousel_design: Array of slide designs (if carousel, else empty)
- visual_requirements: List of MUST-HAVE visual elements
- aspect_ratio_recommendation: "1:1", "9:16", "4:5", or "1.91:1"

Each prompt in image_prompts should be a complete, self-contained paragraph suitable for direct use with an AI image generator.
"""
        return prompt

    def generate_visual_prompt(
        self,
        recommendation: Dict[str, Any],
        entry_plan: Dict[str, Any]
    ) -> VisualPromptOutput:
        # Determine slide count from content structure
        content_structure = recommendation.get('caption_direction', '') or recommendation.get('content', '')
        content_type = entry_plan.get('content_type', 'single_image')
        
        if content_type in ('carousel', 'document_carousel', 'story_sequence'):
            slide_count = self._count_slides_from_content(content_structure)
            slide_count = max(slide_count, 2)  # Carousels have at least 2 slides
        elif content_type in ('reel',):
            slide_count = self._count_slides_from_content(content_structure)
            slide_count = max(slide_count, 1)
        elif content_type in ('story',):
            slide_count = self._count_slides_from_content(content_structure)
        else:
            slide_count = 1

        # Retrieve product visual context
        product = entry_plan.get('product', '')
        if product:
            product_context = self.knowledge_base.query_product_context(
                f"{product} appearance design visual features", n_results=2
            )
        else:
            product_context = self.knowledge_base.query_product_context(
                "Qicdock wireless charger design appearance", n_results=2
            )

        # Retrieve brand visual context
        brand_visual_context = self.knowledge_base.query_brand_context(
            "Qicdock visual identity design language colors minimal", n_results=2
        )

        prompt = self._build_visual_prompt(
            recommendation, entry_plan, product_context, brand_visual_context, slide_count
        )

        logger.info(f"Generating visual prompt for {entry_plan.get('date')} ({entry_plan.get('platform')}) - {entry_plan.get('content_type')} - {slide_count} slides")
        result = self.llm.generate_structured(prompt, VisualPromptOutput, temperature=0.6)
        
        # Ensure image_prompts has at least the hero prompt
        if not result.image_prompts or len(result.image_prompts) == 0:
            result.image_prompts = [result.image_prompt] if result.image_prompt else []
        
        # If the LLM returned fewer prompts than expected, pad with the hero prompt
        while len(result.image_prompts) < slide_count:
            result.image_prompts.append(result.image_prompt)
        
        logger.info(f"Generated {len(result.image_prompts)} image prompts for entry")
        return result


def get_visual_prompt_agent() -> VisualPromptAgent:
    return VisualPromptAgent()